In [4]:
%pip install composable

Requirement already satisfied: composable in /usr/local/lib/python3.12/dist-packages (1.3.0)
Requirement already satisfied: toolz>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from composable) (0.12.1)

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import composable.records as rec

In [7]:
# Standard imports
import polars as pl
import polars.selectors as cs
import seaborn as sns
import numpy as np

from sklearn.preprocessing import StandardScaler

# Pipeline
from sklearn.pipeline import Pipeline


# Preprocessing stuff
from sklearn.preprocessing import LabelEncoder

# Model selection stuff
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate, GridSearchCV

# Classic classifiers
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier


# Metrics to use on the test set
# metric(y_test, y_predict)
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, precision_score, recall_score, roc_auc_score

# Trees and Forests in `sklearn`

In this notebook, we will cover the basics of classification, including:

1. The `DecisionTreeClassifier` and `RandomForestClassifier`.
2. Exploring tuning parameters for each model.
3. Performing a grid search.
4. Additional features of Random Forests.
5. Multiclass problems.

## Classification Example: Kyphosis Data Set

**Problem Statement:**
Given a DataSet of 81 patients who have undergone a spinal surgery for a deformation and the data if the condition recurred, Build a claddification Model to predict whether a patient being admitted for the surgery has chance for recurrence. This model will help the surgeons to plan appropriate level of treatment to prevent recurrence.

**Data Set Description :**
The kyphosis data frame has 81 rows and 4 columns. representing data on children who have had corrective spinal surgery

This data frame contains the following columns/Features:

1. *Kyphosis*: a factor with levels absent present indicating if a kyphosis (a type of deformation) was present after the operation.
2. *Age*: in months
3. *Number*: the number of vertebrae involved
4. *Start*: the number of the first (topmost) vertebra operated on.

**Research Question:** Can we predict whether if kyphosis will be present or absent after the surgery based on the age of the patient, number of vertebrae involved and the first vertebra operated on?

In [11]:
(kyphosis :=
 pl.read_csv('sample_data/kyphosis.csv')
   .drop('rownames')
)

shape: (81, 4)
┌──────────┬─────┬────────┬───────┐
│ Kyphosis ┆ Age ┆ Number ┆ Start │
│ ---      ┆ --- ┆ ---    ┆ ---   │
│ str      ┆ i64 ┆ i64    ┆ i64   │
╞══════════╪═════╪════════╪═══════╡
│ absent   ┆ 71  ┆ 3      ┆ 5     │
│ absent   ┆ 158 ┆ 3      ┆ 14    │
│ present  ┆ 128 ┆ 4      ┆ 5     │
│ absent   ┆ 2   ┆ 5      ┆ 1     │
│ absent   ┆ 1   ┆ 4      ┆ 15    │
│ …        ┆ …   ┆ …      ┆ …     │
│ present  ┆ 157 ┆ 3      ┆ 13    │
│ absent   ┆ 26  ┆ 7      ┆ 13    │
│ absent   ┆ 120 ┆ 2      ┆ 13    │
│ present  ┆ 42  ┆ 7      ┆ 6     │
│ absent   ┆ 36  ┆ 4      ┆ 13    │
└──────────┴─────┴────────┴───────┘

In [12]:
(X_kyphosis :=
 kyphosis
 .drop('Kyphosis')
 .to_pandas()
)

    Age  Number  Start
0    71       3      5
1   158       3     14
2   128       4      5
3     2       5      1
4     1       4     15
..  ...     ...    ...
76  157       3     13
77   26       7     13
78  120       2     13
79   42       7      6
80   36       4     13

[81 rows x 3 columns]

In [13]:
(y_kyphosis :=
 kyphosis
 .get_column('Kyphosis')
 .to_numpy()
 .ravel()
)

array(['absent', 'absent', 'present', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'present', 'present', 'absent',
       'absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'present', 'present', 'absent',
       'present', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'present', 'absent', 'present', 'present', 'absent',
       'absent', 'absent', 'absent', 'present', 'absent', 'absent',
       'present', 'absent', 'absent', 'absent', 'present', 'absent',
       'absent', 'absent', 'absent', 'present', 'absent', 'absent',
       'present', 'present', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'present', 'absent',
       'absent', 'present', 'absent'], dtype=object)

## Topic 1 - Tree and Forest models in `sklearn`

`sklearn` comes with both a tree and forest based classifier, which can be found in the `tree` and `ensemble` submodules, respectively.

In [14]:
(tree := DecisionTreeClassifier(class_weight='balanced')
)

DecisionTreeClassifier(class_weight='balanced')

In [15]:
(forest := RandomForestClassifier(class_weight='balanced')
)

RandomForestClassifier(class_weight='balanced')

## Tuning parameters for trees and forests

First, let's inspect the tuning parameters for each model.

#### Exploring trees

In [ ]:
?tree

Type:        DecisionTreeClassifier
String form: DecisionTreeClassifier(class_weight='balanced')
File:        c:\users\lr7273ow\appdata\local\anaconda3\envs\polars\lib\site-packages\sklearn\tree\_classes.py
Docstring:
A decision tree classifier.

Read more in the :ref:`User Guide <tree>`.

Parameters
----------
criterion : {"gini", "entropy", "log_loss"}, default="gini"
    The function to measure the quality of a split. Supported criteria are
    "gini" for the Gini impurity and "log_loss" and "entropy" both for the
    Shannon information gain, see :ref:`tree_mathematical_formulation`.

splitter : {"best", "random"}, default="best"
    The strategy used to choose the split at each node. Supported
    strategies are "best" to choose the best split and "random" to choose
    the best random split.

max_depth : int, default=None
    The maximum depth of the tree. If None, then nodes are expanded until
    all leaves are pure or until all leaves contain less than
    min_samples_split samples.

min_samples_split : int or float, default=2
    The minimum number of samples required to split an internal node:

    - If int, then consider `min_samples_split` as the minimum number.
    - If float, then `min_samples_split` is a fraction and
      `ceil(min_samples_split * n_samples)` are the minimum
      number of samples for each split.

    .. versionchanged:: 0.18
       Added float values for fractions.

min_samples_leaf : int or float, default=1
    The minimum number of samples required to be at a leaf node.
    A split point at any depth will only be considered if it leaves at
    least ``min_samples_leaf`` training samples in each of the left and
    right branches.  This may have the effect of smoothing the model,
    especially in regression.

    - If int, then consider `min_samples_leaf` as the minimum number.
    - If float, then `min_samples_leaf` is a fraction and
      `ceil(min_samples_leaf * n_samples)` are the minimum
      number of samples for each node.

    .. versionchanged:: 0.18
       Added float values for fractions.

min_weight_fraction_leaf : float, default=0.0
    The minimum weighted fraction of the sum total of weights (of all
    the input samples) required to be at a leaf node. Samples have
    equal weight when sample_weight is not provided.

max_features : int, float or {"sqrt", "log2"}, default=None
    The number of features to consider when looking for the best split:

    - If int, then consider `max_features` features at each split.
    - If float, then `max_features` is a fraction and
      `max(1, int(max_features * n_features_in_))` features are considered at
      each split.
    - If "sqrt", then `max_features=sqrt(n_features)`.
    - If "log2", then `max_features=log2(n_features)`.
    - If None, then `max_features=n_features`.

    .. note::

        The search for a split does not stop until at least one
        valid partition of the node samples is found, even if it requires to
        effectively inspect more than ``max_features`` features.

random_state : int, RandomState instance or None, default=None
    Controls the randomness of the estimator. The features are always
    randomly permuted at each split, even if ``splitter`` is set to
    ``"best"``. When ``max_features < n_features``, the algorithm will
    select ``max_features`` at random at each split before finding the best
    split among them. But the best found split may vary across different
    runs, even if ``max_features=n_features``. That is the case, if the
    improvement of the criterion is identical for several splits and one
    split has to be selected at random. To obtain a deterministic behaviour
    during fitting, ``random_state`` has to be fixed to an integer.
    See :term:`Glossary <random_state>` for details.

max_leaf_nodes : int, default=None
    Grow a tree with ``max_leaf_nodes`` in best-first fashion.
    Best nodes are defined as relative reduction in impurity.
    If None then unlimited number of leaf nodes.

min_impurity_decrease : float, default=0.0
    A node will be split if this split induces a decrease of the impurity
    greater than or equal to this value.

    The weighted impurity decrease equation is the following::

        N_t / N * (impurity - N_t_R / N_t * right_impurity
                            - N_t_L / N_t * left_impurity)

    where ``N`` is the total number of samples, ``N_t`` is the number of
    samples at the current node, ``N_t_L`` is the number of samples in the
    left child, and ``N_t_R`` is the number of samples in the right child.

    ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
    if ``sample_weight`` is passed.

    .. versionadded:: 0.19

class_weight : dict, list of dict or "balanced", default=None
    Weights associated with classes in the form ``{class_label: weight}``.
    If None, all classes are supposed to have weight one. For
    multi-output problems, a list of dicts can be provided in the same
    order as the columns of y.

    Note that for multioutput (including multilabel) weights should be
    defined for each class of every column in its own dict. For example,
    for four-class multilabel classification weights should be
    [{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of
    [{1:1}, {2:5}, {3:1}, {4:1}].

    The "balanced" mode uses the values of y to automatically adjust
    weights inversely proportional to class frequencies in the input data
    as ``n_samples / (n_classes * np.bincount(y))``

    For multi-output, the weights of each column of y will be multiplied.

    Note that these weights will be multiplied with sample_weight (passed
    through the fit method) if sample_weight is specified.

ccp_alpha : non-negative float, default=0.0
    Complexity parameter used for Minimal Cost-Complexity Pruning. The
    subtree with the largest cost complexity that is smaller than
    ``ccp_alpha`` will be chosen. By default, no pruning is performed. See
    :ref:`minimal_cost_complexity_pruning` for details. See
    :ref:`sphx_glr_auto_examples_tree_plot_cost_complexity_pruning.py`
    for an example of such pruning.

    .. versionadded:: 0.22

monotonic_cst : array-like of int of shape (n_features), default=None
    Indicates the monotonicity constraint to enforce on each feature.
      - 1: monotonic increase
      - 0: no constraint
      - -1: monotonic decrease

    If monotonic_cst is None, no constraints are applied.

    Monotonicity constraints are not supported for:
      - multiclass classifications (i.e. when `n_classes > 2`),
      - multioutput classifications (i.e. when `n_outputs_ > 1`),
      - classifications trained on data with missing values.

    The constraints hold over the probability of the positive class.

    Read more in the :ref:`User Guide <monotonic_cst_gbdt>`.

    .. versionadded:: 1.4

Attributes
----------
classes_ : ndarray of shape (n_classes,) or list of ndarray
    The classes labels (single output problem),
    or a list of arrays of class labels (multi-output problem).

feature_importances_ : ndarray of shape (n_features,)
    The impurity-based feature importances.
    The higher, the more important the feature.
    The importance of a feature is computed as the (normalized)
    total reduction of the criterion brought by that feature.  It is also
    known as the Gini importance [4]_.

    Warning: impurity-based feature importances can be misleading for
    high cardinality features (many unique values). See
    :func:`sklearn.inspection.permutation_importance` as an alternative.

max_features_ : int
    The inferred value of max_features.

n_classes_ : int or list of int
    The number of classes (for single output problems),
    or a list containing the number of classes for each
    output (for multi-output problems).

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

n_outputs_ : int
    The number of outputs when ``fit`` is performed.

tree_ : Tree instance
    The underlying Tree object. Please refer to
    ``help(sklearn.tree._tree.Tree)`` for attributes of Tree object and
    :ref:`sphx_glr_auto_examples_tree_plot_unveil_tree_structure.py`
    for basic usage of these attributes.

See Also
--------
DecisionTreeRegressor : A decision tree regressor.

Notes
-----
The default values for the parameters controlling the size of the trees
(e.g. ``max_depth``, ``min_samples_leaf``, etc.) lead to fully grown and
unpruned trees which can potentially be very large on some data sets. To
reduce memory consumption, the complexity and size of the trees should be
controlled by setting those parameter values.

The :meth:`predict` method operates using the :func:`numpy.argmax`
function on the outputs of :meth:`predict_proba`. This means that in
case the highest predicted probabilities are tied, the classifier will
predict the tied class with the lowest index in :term:`classes_`.

References
----------

.. [1] https://en.wikipedia.org/wiki/Decision_tree_learning

.. [2] L. Breiman, J. Friedman, R. Olshen, and C. Stone, "Classification
       and Regression Trees", Wadsworth, Belmont, CA, 1984.

.. [3] T. Hastie, R. Tibshirani and J. Friedman. "Elements of Statistical
       Learning", Springer, 2009.

.. [4] L. Breiman, and A. Cutler, "Random Forests",
       https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm

Examples
--------
>>> from sklearn.datasets import load_iris
>>> from sklearn.model_selection import cross_val_score
>>> from sklearn.tree import DecisionTreeClassifier
>>> clf = DecisionTreeClassifier(random_state=0)
>>> iris = load_iris()
>>> cross_val_score(clf, iris.data, iris.target, cv=10)
...                             # doctest: +SKIP
...
array([ 1.     ,  0.93,  0.86,  0.93,  0.93,
        0.93,  0.93,  1.     ,  0.93,  1.      ])

In [16]:
tree.get_params()

{'ccp_alpha': 0.0,
 'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [17]:
(tree_grid :=
 {'min_samples_leaf': [1,2,3],
  'min_samples_split': [2,3,4],
  'max_depth': [3,4,5],
 }
)

{'min_samples_leaf': [1, 2, 3],
 'min_samples_split': [2, 3, 4],
 'max_depth': [3, 4, 5]}

In [18]:
folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [19]:
grid_search_tree = GridSearchCV(tree, tree_grid, cv = folds, scoring='roc_auc', n_jobs=-1, verbose=1)

grid_search_tree.fit(X_kyphosis, y_kyphosis)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=DecisionTreeClassifier(class_weight='balanced'),
             n_jobs=-1,
             param_grid={'max_depth': [3, 4, 5], 'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [2, 3, 4]},
             scoring='roc_auc', verbose=1)

In [20]:
?cross_validate

In [21]:
my_scores = ['accuracy', 'balanced_accuracy', 'roc_auc']

(tree_scores :=
 cross_validate(grid_search_tree, X_kyphosis, y_kyphosis,
                cv = folds,
                scoring=my_scores,
                verbose=0,
                n_jobs=-1,
                )
 >> rec.subset([f'test_{m}' for m in my_scores])
 >> rec.map(np.mean)
)

{'test_accuracy': np.float64(0.7176470588235294),
 'test_balanced_accuracy': np.float64(0.6576923076923077),
 'test_roc_auc': np.float64(0.7057692307692307)}

#### Exploring forests

In [13]:
?forest

Object `forest` not found.

In [22]:
forest.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [23]:
(forest_grid :=
{'max_depth': [2,3,4,5],
 'min_samples_leaf': [1,2,3],
 'min_samples_split': [2,3,4],
 'n_estimators': [10, 100, 500],
 }
)

{'max_depth': [2, 3, 4, 5],
 'min_samples_leaf': [1, 2, 3],
 'min_samples_split': [2, 3, 4],
 'n_estimators': [10, 100, 500]}

In [24]:
grid_search_forest = GridSearchCV(forest, forest_grid, cv = folds, scoring='roc_auc', n_jobs=-1, verbose=1)

grid_search_forest.fit(X_kyphosis, y_kyphosis)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=RandomForestClassifier(class_weight='balanced'),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 4, 5],
                         'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [2, 3, 4],
                         'n_estimators': [10, 100, 500]},
             scoring='roc_auc', verbose=1)

In [25]:
(forest_scores :=
 cross_validate(grid_search_tree, X_kyphosis, y_kyphosis,
                cv = folds,
                scoring=my_scores,
                verbose=0,
                n_jobs=-1,
                )
 >> rec.subset([f'test_{m}' for m in my_scores])
 >> rec.map(np.mean)
)

{'test_accuracy': np.float64(0.7176470588235294),
 'test_balanced_accuracy': np.float64(0.6576923076923077),
 'test_roc_auc': np.float64(0.6916666666666667)}

## Topic 3 - Extra random forest features

As you learned from your out of class videos, the fact that random forests uses bagging allows for extra functionality, including

1. A measure of variable importance, and
2. An out of the box objective measurement of model fit.

#### Variable importance

In [26]:
grid_search_forest.best_estimator_.feature_importances_ # Ugh! so unreadable!

array([0.32353627, 0.21716972, 0.459294  ])

In [27]:
(feat_imp :=
 pl.DataFrame({'columns':grid_search_forest.feature_names_in_,
               'importance':grid_search_forest.best_estimator_.feature_importances_},
             )
   .sort('importance', descending=True)
)

shape: (3, 2)
┌─────────┬────────────┐
│ columns ┆ importance │
│ ---     ┆ ---        │
│ str     ┆ f64        │
╞═════════╪════════════╡
│ Start   ┆ 0.459294   │
│ Age     ┆ 0.323536   │
│ Number  ┆ 0.21717    │
└─────────┴────────────┘

#### Out of bag error estimate

**Notes.**

1. You need to set `oob_score=True` when creating the forest to get this measure.
2. Computing the `oob_score` has some overhead, so it is best leave this off when performing a grid search.  Instead, refit the winning model with this flag after.

In [28]:
grid_search_forest.best_params_

{'max_depth': 2,
 'min_samples_leaf': 3,
 'min_samples_split': 3,
 'n_estimators': 100}

In [29]:
(winning_forest_w_oob_error :=
 RandomForestClassifier(oob_score=True,

                       **grid_search_forest.best_params_,
                      )

)

RandomForestClassifier(max_depth=2, min_samples_leaf=3, min_samples_split=3,
                       oob_score=True)

In [30]:
winning_forest_w_oob_error.fit(X_kyphosis, y_kyphosis)

winning_forest_w_oob_error.oob_score_

0.7901234567901234

## Topic 4 - Multiclass classification

In [31]:
(olive_oil :=
 pl.read_csv("sample_data/OliveOils.csv")
).head(2)

shape: (2, 8)
┌──────────────┬──────────┬─────────────┬──────────┬───────┬──────────┬────────────┬───────────┐
│ Area.name    ┆ palmitic ┆ palmitoleic ┆ strearic ┆ oleic ┆ linoleic ┆ eicosanoic ┆ linolenic │
│ ---          ┆ ---      ┆ ---         ┆ ---      ┆ ---   ┆ ---      ┆ ---        ┆ ---       │
│ str          ┆ i64      ┆ i64         ┆ i64      ┆ i64   ┆ i64      ┆ i64        ┆ i64       │
╞══════════════╪══════════╪═════════════╪══════════╪═══════╪══════════╪════════════╪═══════════╡
│ North-Apulia ┆ 1075     ┆ 75          ┆ 226      ┆ 7823  ┆ 672      ┆ 36         ┆ 60        │
│ North-Apulia ┆ 1088     ┆ 73          ┆ 224      ┆ 7709  ┆ 781      ┆ 31         ┆ 61        │
└──────────────┴──────────┴─────────────┴──────────┴───────┴──────────┴────────────┴───────────┘

In [32]:
(X_oil :=
 olive_oil
 .drop('Area.name')
 .to_pandas()
).head(2)

   palmitic  palmitoleic  strearic  oleic  linoleic  eicosanoic  linolenic
0      1075           75       226   7823       672          36         60
1      1088           73       224   7709       781          31         61

In [33]:
(y_oil :=
 olive_oil
 .select('Area.name')
 .to_numpy()
 .ravel()
)[:3]

array(['North-Apulia', 'North-Apulia', 'North-Apulia'], dtype=object)

In [34]:
X_train_oil, X_test_oil, y_train_oil, y_test_oil = train_test_split(X_oil, y_oil, test_size=0.3, random_state=42, stratify=y_oil)

In [35]:
grid_search_tree_MC = GridSearchCV(tree, tree_grid, cv = folds, scoring='balanced_accuracy', n_jobs=-1, verbose=0)

grid_search_tree_MC.fit(X_train_oil, y_train_oil)
grid_search_tree_MC.score(X_test_oil, y_test_oil)

np.float64(0.7979253089310016)

In [36]:
grid_search_forest_MC = GridSearchCV(forest, forest_grid, cv = folds, scoring='balanced_accuracy', n_jobs=-1, verbose=0)

grid_search_forest_MC.fit(X_train_oil, y_train_oil)
grid_search_forest_MC.score(X_test_oil, y_test_oil)

np.float64(0.8902578691952505)

## <font color='red'> Exercise 1 </font>

Do some sleuthing to determine the impact of various tuning parameters for both trees and forests on the model flexibility and overfitting.

<font color='orange'>
A summary of your findings here.
</font>

In [ ]:
?tree

Type:        DecisionTreeClassifier
String form: DecisionTreeClassifier(class_weight='balanced')
File:        c:\users\lr7273ow\appdata\local\anaconda3\envs\polars\lib\site-packages\sklearn\tree\_classes.py
Docstring:
A decision tree classifier.

Read more in the :ref:`User Guide <tree>`.

Parameters
----------
criterion : {"gini", "entropy", "log_loss"}, default="gini"
    The function to measure the quality of a split. Supported criteria are
    "gini" for the Gini impurity and "log_loss" and "entropy" both for the
    Shannon information gain, see :ref:`tree_mathematical_formulation`.

splitter : {"best", "random"}, default="best"
    The strategy used to choose the split at each node. Supported
    strategies are "best" to choose the best split and "random" to choose
    the best random split.

max_depth : int, default=None
    The maximum depth of the tree. If None, then nodes are expanded until
    all leaves are pure or until all leaves contain less than
    min_samples_split samples.

min_samples_split : int or float, default=2
    The minimum number of samples required to split an internal node:

    - If int, then consider `min_samples_split` as the minimum number.
    - If float, then `min_samples_split` is a fraction and
      `ceil(min_samples_split * n_samples)` are the minimum
      number of samples for each split.

    .. versionchanged:: 0.18
       Added float values for fractions.

min_samples_leaf : int or float, default=1
    The minimum number of samples required to be at a leaf node.
    A split point at any depth will only be considered if it leaves at
    least ``min_samples_leaf`` training samples in each of the left and
    right branches.  This may have the effect of smoothing the model,
    especially in regression.

    - If int, then consider `min_samples_leaf` as the minimum number.
    - If float, then `min_samples_leaf` is a fraction and
      `ceil(min_samples_leaf * n_samples)` are the minimum
      number of samples for each node.

    .. versionchanged:: 0.18
       Added float values for fractions.

min_weight_fraction_leaf : float, default=0.0
    The minimum weighted fraction of the sum total of weights (of all
    the input samples) required to be at a leaf node. Samples have
    equal weight when sample_weight is not provided.

max_features : int, float or {"sqrt", "log2"}, default=None
    The number of features to consider when looking for the best split:

    - If int, then consider `max_features` features at each split.
    - If float, then `max_features` is a fraction and
      `max(1, int(max_features * n_features_in_))` features are considered at
      each split.
    - If "sqrt", then `max_features=sqrt(n_features)`.
    - If "log2", then `max_features=log2(n_features)`.
    - If None, then `max_features=n_features`.

    .. note::

        The search for a split does not stop until at least one
        valid partition of the node samples is found, even if it requires to
        effectively inspect more than ``max_features`` features.

random_state : int, RandomState instance or None, default=None
    Controls the randomness of the estimator. The features are always
    randomly permuted at each split, even if ``splitter`` is set to
    ``"best"``. When ``max_features < n_features``, the algorithm will
    select ``max_features`` at random at each split before finding the best
    split among them. But the best found split may vary across different
    runs, even if ``max_features=n_features``. That is the case, if the
    improvement of the criterion is identical for several splits and one
    split has to be selected at random. To obtain a deterministic behaviour
    during fitting, ``random_state`` has to be fixed to an integer.
    See :term:`Glossary <random_state>` for details.

max_leaf_nodes : int, default=None
    Grow a tree with ``max_leaf_nodes`` in best-first fashion.
    Best nodes are defined as relative reduction in impurity.
    If None then unlimited number of leaf nodes.

min_impurity_decrease : float, default=0.0
    A node will be split if this split induces a decrease of the impurity
    greater than or equal to this value.

    The weighted impurity decrease equation is the following::

        N_t / N * (impurity - N_t_R / N_t * right_impurity
                            - N_t_L / N_t * left_impurity)

    where ``N`` is the total number of samples, ``N_t`` is the number of
    samples at the current node, ``N_t_L`` is the number of samples in the
    left child, and ``N_t_R`` is the number of samples in the right child.

    ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
    if ``sample_weight`` is passed.

    .. versionadded:: 0.19

class_weight : dict, list of dict or "balanced", default=None
    Weights associated with classes in the form ``{class_label: weight}``.
    If None, all classes are supposed to have weight one. For
    multi-output problems, a list of dicts can be provided in the same
    order as the columns of y.

    Note that for multioutput (including multilabel) weights should be
    defined for each class of every column in its own dict. For example,
    for four-class multilabel classification weights should be
    [{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of
    [{1:1}, {2:5}, {3:1}, {4:1}].

    The "balanced" mode uses the values of y to automatically adjust
    weights inversely proportional to class frequencies in the input data
    as ``n_samples / (n_classes * np.bincount(y))``

    For multi-output, the weights of each column of y will be multiplied.

    Note that these weights will be multiplied with sample_weight (passed
    through the fit method) if sample_weight is specified.

ccp_alpha : non-negative float, default=0.0
    Complexity parameter used for Minimal Cost-Complexity Pruning. The
    subtree with the largest cost complexity that is smaller than
    ``ccp_alpha`` will be chosen. By default, no pruning is performed. See
    :ref:`minimal_cost_complexity_pruning` for details. See
    :ref:`sphx_glr_auto_examples_tree_plot_cost_complexity_pruning.py`
    for an example of such pruning.

    .. versionadded:: 0.22

monotonic_cst : array-like of int of shape (n_features), default=None
    Indicates the monotonicity constraint to enforce on each feature.
      - 1: monotonic increase
      - 0: no constraint
      - -1: monotonic decrease

    If monotonic_cst is None, no constraints are applied.

    Monotonicity constraints are not supported for:
      - multiclass classifications (i.e. when `n_classes > 2`),
      - multioutput classifications (i.e. when `n_outputs_ > 1`),
      - classifications trained on data with missing values.

    The constraints hold over the probability of the positive class.

    Read more in the :ref:`User Guide <monotonic_cst_gbdt>`.

    .. versionadded:: 1.4

Attributes
----------
classes_ : ndarray of shape (n_classes,) or list of ndarray
    The classes labels (single output problem),
    or a list of arrays of class labels (multi-output problem).

feature_importances_ : ndarray of shape (n_features,)
    The impurity-based feature importances.
    The higher, the more important the feature.
    The importance of a feature is computed as the (normalized)
    total reduction of the criterion brought by that feature.  It is also
    known as the Gini importance [4]_.

    Warning: impurity-based feature importances can be misleading for
    high cardinality features (many unique values). See
    :func:`sklearn.inspection.permutation_importance` as an alternative.

max_features_ : int
    The inferred value of max_features.

n_classes_ : int or list of int
    The number of classes (for single output problems),
    or a list containing the number of classes for each
    output (for multi-output problems).

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

n_outputs_ : int
    The number of outputs when ``fit`` is performed.

tree_ : Tree instance
    The underlying Tree object. Please refer to
    ``help(sklearn.tree._tree.Tree)`` for attributes of Tree object and
    :ref:`sphx_glr_auto_examples_tree_plot_unveil_tree_structure.py`
    for basic usage of these attributes.

See Also
--------
DecisionTreeRegressor : A decision tree regressor.

Notes
-----
The default values for the parameters controlling the size of the trees
(e.g. ``max_depth``, ``min_samples_leaf``, etc.) lead to fully grown and
unpruned trees which can potentially be very large on some data sets. To
reduce memory consumption, the complexity and size of the trees should be
controlled by setting those parameter values.

The :meth:`predict` method operates using the :func:`numpy.argmax`
function on the outputs of :meth:`predict_proba`. This means that in
case the highest predicted probabilities are tied, the classifier will
predict the tied class with the lowest index in :term:`classes_`.

References
----------

.. [1] https://en.wikipedia.org/wiki/Decision_tree_learning

.. [2] L. Breiman, J. Friedman, R. Olshen, and C. Stone, "Classification
       and Regression Trees", Wadsworth, Belmont, CA, 1984.

.. [3] T. Hastie, R. Tibshirani and J. Friedman. "Elements of Statistical
       Learning", Springer, 2009.

.. [4] L. Breiman, and A. Cutler, "Random Forests",
       https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm

Examples
--------
>>> from sklearn.datasets import load_iris
>>> from sklearn.model_selection import cross_val_score
>>> from sklearn.tree import DecisionTreeClassifier
>>> clf = DecisionTreeClassifier(random_state=0)
>>> iris = load_iris()
>>> cross_val_score(clf, iris.data, iris.target, cv=10)
...                             # doctest: +SKIP
...
array([ 1.     ,  0.93,  0.86,  0.93,  0.93,
        0.93,  0.93,  1.     ,  0.93,  1.      ])

In [33]:
tree.get_params()

{'ccp_alpha': 0.0,
 'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [ ]:
?forest

Type:        RandomForestClassifier
String form: RandomForestClassifier(class_weight='balanced')
File:        c:\users\lr7273ow\appdata\local\anaconda3\envs\polars\lib\site-packages\sklearn\ensemble\_forest.py
Docstring:
A random forest classifier.

A random forest is a meta estimator that fits a number of decision tree
classifiers on various sub-samples of the dataset and uses averaging to
improve the predictive accuracy and control over-fitting.
Trees in the forest use the best split strategy, i.e. equivalent to passing
`splitter="best"` to the underlying :class:`~sklearn.tree.DecisionTreeClassifier`.
The sub-sample size is controlled with the `max_samples` parameter if
`bootstrap=True` (default), otherwise the whole dataset is used to build
each tree.

For a comparison between tree-based ensemble models see the example
:ref:`sphx_glr_auto_examples_ensemble_plot_forest_hist_grad_boosting_comparison.py`.

This estimator has native support for missing values (NaNs). During training,
the tree grower learns at each split point whether samples with missing values
should go to the left or right child, based on the potential gain. When predicting,
samples with missing values are assigned to the left or right child consequently.
If no missing values were encountered for a given feature during training, then
samples with missing values are mapped to whichever child has the most samples.

Read more in the :ref:`User Guide <forest>`.

Parameters
----------
n_estimators : int, default=100
    The number of trees in the forest.

    .. versionchanged:: 0.22
       The default value of ``n_estimators`` changed from 10 to 100
       in 0.22.

criterion : {"gini", "entropy", "log_loss"}, default="gini"
    The function to measure the quality of a split. Supported criteria are
    "gini" for the Gini impurity and "log_loss" and "entropy" both for the
    Shannon information gain, see :ref:`tree_mathematical_formulation`.
    Note: This parameter is tree-specific.

max_depth : int, default=None
    The maximum depth of the tree. If None, then nodes are expanded until
    all leaves are pure or until all leaves contain less than
    min_samples_split samples.

min_samples_split : int or float, default=2
    The minimum number of samples required to split an internal node:

    - If int, then consider `min_samples_split` as the minimum number.
    - If float, then `min_samples_split` is a fraction and
      `ceil(min_samples_split * n_samples)` are the minimum
      number of samples for each split.

    .. versionchanged:: 0.18
       Added float values for fractions.

min_samples_leaf : int or float, default=1
    The minimum number of samples required to be at a leaf node.
    A split point at any depth will only be considered if it leaves at
    least ``min_samples_leaf`` training samples in each of the left and
    right branches.  This may have the effect of smoothing the model,
    especially in regression.

    - If int, then consider `min_samples_leaf` as the minimum number.
    - If float, then `min_samples_leaf` is a fraction and
      `ceil(min_samples_leaf * n_samples)` are the minimum
      number of samples for each node.

    .. versionchanged:: 0.18
       Added float values for fractions.

min_weight_fraction_leaf : float, default=0.0
    The minimum weighted fraction of the sum total of weights (of all
    the input samples) required to be at a leaf node. Samples have
    equal weight when sample_weight is not provided.

max_features : {"sqrt", "log2", None}, int or float, default="sqrt"
    The number of features to consider when looking for the best split:

    - If int, then consider `max_features` features at each split.
    - If float, then `max_features` is a fraction and
      `max(1, int(max_features * n_features_in_))` features are considered at each
      split.
    - If "sqrt", then `max_features=sqrt(n_features)`.
    - If "log2", then `max_features=log2(n_features)`.
    - If None, then `max_features=n_features`.

    .. versionchanged:: 1.1
        The default of `max_features` changed from `"auto"` to `"sqrt"`.

    Note: the search for a split does not stop until at least one
    valid partition of the node samples is found, even if it requires to
    effectively inspect more than ``max_features`` features.

max_leaf_nodes : int, default=None
    Grow trees with ``max_leaf_nodes`` in best-first fashion.
    Best nodes are defined as relative reduction in impurity.
    If None then unlimited number of leaf nodes.

min_impurity_decrease : float, default=0.0
    A node will be split if this split induces a decrease of the impurity
    greater than or equal to this value.

    The weighted impurity decrease equation is the following::

        N_t / N * (impurity - N_t_R / N_t * right_impurity
                            - N_t_L / N_t * left_impurity)

    where ``N`` is the total number of samples, ``N_t`` is the number of
    samples at the current node, ``N_t_L`` is the number of samples in the
    left child, and ``N_t_R`` is the number of samples in the right child.

    ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
    if ``sample_weight`` is passed.

    .. versionadded:: 0.19

bootstrap : bool, default=True
    Whether bootstrap samples are used when building trees. If False, the
    whole dataset is used to build each tree.

oob_score : bool or callable, default=False
    Whether to use out-of-bag samples to estimate the generalization score.
    By default, :func:`~sklearn.metrics.accuracy_score` is used.
    Provide a callable with signature `metric(y_true, y_pred)` to use a
    custom metric. Only available if `bootstrap=True`.

    For an illustration of out-of-bag (OOB) error estimation, see the example
    :ref:`sphx_glr_auto_examples_ensemble_plot_ensemble_oob.py`.

n_jobs : int, default=None
    The number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,
    :meth:`decision_path` and :meth:`apply` are all parallelized over the
    trees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`
    context. ``-1`` means using all processors. See :term:`Glossary
    <n_jobs>` for more details.

random_state : int, RandomState instance or None, default=None
    Controls both the randomness of the bootstrapping of the samples used
    when building trees (if ``bootstrap=True``) and the sampling of the
    features to consider when looking for the best split at each node
    (if ``max_features < n_features``).
    See :term:`Glossary <random_state>` for details.

verbose : int, default=0
    Controls the verbosity when fitting and predicting.

warm_start : bool, default=False
    When set to ``True``, reuse the solution of the previous call to fit
    and add more estimators to the ensemble, otherwise, just fit a whole
    new forest. See :term:`Glossary <warm_start>` and
    :ref:`tree_ensemble_warm_start` for details.

class_weight : {"balanced", "balanced_subsample"}, dict or list of dicts,             default=None
    Weights associated with classes in the form ``{class_label: weight}``.
    If not given, all classes are supposed to have weight one. For
    multi-output problems, a list of dicts can be provided in the same
    order as the columns of y.

    Note that for multioutput (including multilabel) weights should be
    defined for each class of every column in its own dict. For example,
    for four-class multilabel classification weights should be
    [{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of
    [{1:1}, {2:5}, {3:1}, {4:1}].

    The "balanced" mode uses the values of y to automatically adjust
    weights inversely proportional to class frequencies in the input data
    as ``n_samples / (n_classes * np.bincount(y))``

    The "balanced_subsample" mode is the same as "balanced" except that
    weights are computed based on the bootstrap sample for every tree
    grown.

    For multi-output, the weights of each column of y will be multiplied.

    Note that these weights will be multiplied with sample_weight (passed
    through the fit method) if sample_weight is specified.

ccp_alpha : non-negative float, default=0.0
    Complexity parameter used for Minimal Cost-Complexity Pruning. The
    subtree with the largest cost complexity that is smaller than
    ``ccp_alpha`` will be chosen. By default, no pruning is performed. See
    :ref:`minimal_cost_complexity_pruning` for details. See
    :ref:`sphx_glr_auto_examples_tree_plot_cost_complexity_pruning.py`
    for an example of such pruning.

    .. versionadded:: 0.22

max_samples : int or float, default=None
    If bootstrap is True, the number of samples to draw from X
    to train each base estimator.

    - If None (default), then draw `X.shape[0]` samples.
    - If int, then draw `max_samples` samples.
    - If float, then draw `max(round(n_samples * max_samples), 1)` samples. Thus,
      `max_samples` should be in the interval `(0.0, 1.0]`.

    .. versionadded:: 0.22

monotonic_cst : array-like of int of shape (n_features), default=None
    Indicates the monotonicity constraint to enforce on each feature.
      - 1: monotonic increase
      - 0: no constraint
      - -1: monotonic decrease

    If monotonic_cst is None, no constraints are applied.

    Monotonicity constraints are not supported for:
      - multiclass classifications (i.e. when `n_classes > 2`),
      - multioutput classifications (i.e. when `n_outputs_ > 1`),
      - classifications trained on data with missing values.

    The constraints hold over the probability of the positive class.

    Read more in the :ref:`User Guide <monotonic_cst_gbdt>`.

    .. versionadded:: 1.4

Attributes
----------
estimator_ : :class:`~sklearn.tree.DecisionTreeClassifier`
    The child estimator template used to create the collection of fitted
    sub-estimators.

    .. versionadded:: 1.2
       `base_estimator_` was renamed to `estimator_`.

estimators_ : list of DecisionTreeClassifier
    The collection of fitted sub-estimators.

classes_ : ndarray of shape (n_classes,) or a list of such arrays
    The classes labels (single output problem), or a list of arrays of
    class labels (multi-output problem).

n_classes_ : int or list
    The number of classes (single output problem), or a list containing the
    number of classes for each output (multi-output problem).

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

n_outputs_ : int
    The number of outputs when ``fit`` is performed.

feature_importances_ : ndarray of shape (n_features,)
    The impurity-based feature importances.
    The higher, the more important the feature.
    The importance of a feature is computed as the (normalized)
    total reduction of the criterion brought by that feature.  It is also
    known as the Gini importance.

    Warning: impurity-based feature importances can be misleading for
    high cardinality features (many unique values). See
    :func:`sklearn.inspection.permutation_importance` as an alternative.

oob_score_ : float
    Score of the training dataset obtained using an out-of-bag estimate.
    This attribute exists only when ``oob_score`` is True.

oob_decision_function_ : ndarray of shape (n_samples, n_classes) or             (n_samples, n_classes, n_outputs)
    Decision function computed with out-of-bag estimate on the training
    set. If n_estimators is small it might be possible that a data point
    was never left out during the bootstrap. In this case,
    `oob_decision_function_` might contain NaN. This attribute exists
    only when ``oob_score`` is True.

estimators_samples_ : list of arrays
    The subset of drawn samples (i.e., the in-bag samples) for each base
    estimator. Each subset is defined by an array of the indices selected.

    .. versionadded:: 1.4

See Also
--------
sklearn.tree.DecisionTreeClassifier : A decision tree classifier.
sklearn.ensemble.ExtraTreesClassifier : Ensemble of extremely randomized
    tree classifiers.
sklearn.ensemble.HistGradientBoostingClassifier : A Histogram-based Gradient
    Boosting Classification Tree, very fast for big datasets (n_samples >=
    10_000).

Notes
-----
The default values for the parameters controlling the size of the trees
(e.g. ``max_depth``, ``min_samples_leaf``, etc.) lead to fully grown and
unpruned trees which can potentially be very large on some data sets. To
reduce memory consumption, the complexity and size of the trees should be
controlled by setting those parameter values.

The features are always randomly permuted at each split. Therefore,
the best found split may vary, even with the same training data,
``max_features=n_features`` and ``bootstrap=False``, if the improvement
of the criterion is identical for several splits enumerated during the
search of the best split. To obtain a deterministic behaviour during
fitting, ``random_state`` has to be fixed.

References
----------
.. [1] :doi:`L. Breiman, "Random Forests", Machine Learning, 45(1), 5-32, 2001.
       <10.1023/A:1010933404324>`

Examples
--------
>>> from sklearn.ensemble import RandomForestClassifier
>>> from sklearn.datasets import make_classification
>>> X, y = make_classification(n_samples=1000, n_features=4,
...                            n_informative=2, n_redundant=0,
...                            random_state=0, shuffle=False)
>>> clf = RandomForestClassifier(max_depth=2, random_state=0)
>>> clf.fit(X, y)
RandomForestClassifier(...)
>>> print(clf.predict([[0, 0, 0, 0]]))
[1]

 #### The impact of certain parameters for the tree classification model such as criterion, splitter and max_depth params. The ccp_alpha parameter is able to chop off branches that don't add predictive power uses the measure to the quality of a split, the min_samples_leaf is used to choose the split at each node, and the max_depth (which is the most important) deals with overfitting.

#### The impact of certain parameters for the forest classification model such as n_estimator determines  the number of trees, the max features how many limits each tree can look for a split, and the bootstrap as the tree uses sub-samples which averages out the mean between trees.

## <font color="red"> Exercise 2 </font>

1. Use a combined grid search to compare the performance of trees and forests on the Pima Indian diabetes data set.  
2. Validate the winning model by computing CV scores on the test set.
3. Use random forests to explore the feature importance.  If a forest wasn't the winning model, redo the grid search to find the best forest.
4. Comment on your findings.

In [39]:
(
    diabetes :=
 pl.read_csv('sample_data/diabetes_raw.csv')
)

shape: (768, 9)
┌─────────────┬─────────┬───────────────┬───────────────┬───┬──────┬──────────────┬─────┬──────────┐
│ Pregnancies ┆ Glucose ┆ BloodPressure ┆ SkinThickness ┆ … ┆ BMI  ┆ DiabetesPedi ┆ Age ┆ Diabetes │
│ ---         ┆ ---     ┆ ---           ┆ ---           ┆   ┆ ---  ┆ greeFunction ┆ --- ┆ ---      │
│ i64         ┆ i64     ┆ i64           ┆ i64           ┆   ┆ f64  ┆ ---          ┆ i64 ┆ str      │
│             ┆         ┆               ┆               ┆   ┆      ┆ f64          ┆     ┆          │
╞═════════════╪═════════╪═══════════════╪═══════════════╪═══╪══════╪══════════════╪═════╪══════════╡
│ 6           ┆ 148     ┆ 72            ┆ 35            ┆ … ┆ 33.6 ┆ 0.627        ┆ 50  ┆ Yes      │
│ 1           ┆ 85      ┆ 66            ┆ 29            ┆ … ┆ 26.6 ┆ 0.351        ┆ 31  ┆ No       │
│ 8           ┆ 183     ┆ 64            ┆ 0             ┆ … ┆ 23.3 ┆ 0.672        ┆ 32  ┆ Yes      │
│ 1           ┆ 89      ┆ 66            ┆ 23            ┆ … ┆ 28.1 ┆ 0.167        ┆ 21  ┆ No       │
│ 0           ┆ 137     ┆ 40            ┆ 35            ┆ … ┆ 43.1 ┆ 2.288        ┆ 33  ┆ Yes      │
│ …           ┆ …       ┆ …             ┆ …             ┆ … ┆ …    ┆ …            ┆ …   ┆ …        │
│ 10          ┆ 101     ┆ 76            ┆ 48            ┆ … ┆ 32.9 ┆ 0.171        ┆ 63  ┆ No       │
│ 2           ┆ 122     ┆ 70            ┆ 27            ┆ … ┆ 36.8 ┆ 0.34         ┆ 27  ┆ No       │
│ 5           ┆ 121     ┆ 72            ┆ 23            ┆ … ┆ 26.2 ┆ 0.245        ┆ 30  ┆ No       │
│ 1           ┆ 126     ┆ 60            ┆ 0             ┆ … ┆ 30.1 ┆ 0.349        ┆ 47  ┆ Yes      │
│ 1           ┆ 93      ┆ 70            ┆ 31            ┆ … ┆ 30.4 ┆ 0.315        ┆ 23  ┆ No       │
└─────────────┴─────────┴───────────────┴───────────────┴───┴──────┴──────────────┴─────┴──────────┘

In [40]:
(X_diabetes :=
    diabetes
    .drop('Diabetes')
    .to_pandas()
 )

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [41]:
( y_diabetes :=
       diabetes
       .select('Diabetes')
       .to_pandas()
)

    Diabetes
0        Yes
1         No
2        Yes
3         No
4        Yes
..       ...
763       No
764       No
765       No
766      Yes
767       No

[768 rows x 1 columns]

In [42]:
X_train_diabetes, X_test_diabetes, y_train_diabetes, y_test_diabetes = train_test_split(X_diabetes,y_diabetes, test_size=0.3, random_state=42)

In [43]:
folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [44]:
(tree := DecisionTreeClassifier(class_weight = 'balanced')
)

DecisionTreeClassifier(class_weight='balanced')

In [45]:
grid_search_forest = GridSearchCV(forest, forest_grid, cv = folds, scoring='roc_auc', n_jobs=-1, verbose=1)

grid_search_forest.fit(X_diabetes, y_diabetes)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=RandomForestClassifier(class_weight='balanced'),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 4, 5],
                         'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [2, 3, 4],
                         'n_estimators': [10, 100, 500]},
             scoring='roc_auc', verbose=1)

In [46]:
(tree_grid :=
  { 'classifier': [DecisionTreeClassifier()], # Kept in a list to avoid that previous error!
    'classifier__min_samples_leaf': [1, 2, 3],
    'classifier__min_samples_split': [2, 3, 4],
    'classifier__max_depth': [3, 4, 5]
 }
)

{'classifier': [DecisionTreeClassifier()],
 'classifier__min_samples_leaf': [1, 2, 3],
 'classifier__min_samples_split': [2, 3, 4],
 'classifier__max_depth': [3, 4, 5]}

In [47]:
(forest_grid :=
{
    'classifier': [RandomForestClassifier()], # Added the 's' in classifier
    'classifier__max_depth': [2, 3, 4, 5],
    'classifier__min_samples_leaf': [1, 2, 3],
    'classifier__min_samples_split': [2, 3, 4],
    'classifier__n_estimators': [10, 100, 500]
}
)

{'classifier': [RandomForestClassifier()],
 'classifier__max_depth': [2, 3, 4, 5],
 'classifier__min_samples_leaf': [1, 2, 3],
 'classifier__min_samples_split': [2, 3, 4],
 'classifier__n_estimators': [10, 100, 500]}

In [48]:
(generic_cls :=
 Pipeline(steps = [
     ('scaler', StandardScaler()),
     ('classifier', None)  # <-- classifier goes here
 ])

)

Pipeline(steps=[('scaler', StandardScaler()), ('classifier', None)])

In [49]:
(combined_grid :=

 [forest_grid, tree_grid]


)

[{'classifier': [RandomForestClassifier()],
  'classifier__max_depth': [2, 3, 4, 5],
  'classifier__min_samples_leaf': [1, 2, 3],
  'classifier__min_samples_split': [2, 3, 4],
  'classifier__n_estimators': [10, 100, 500]},
 {'classifier': [DecisionTreeClassifier()],
  'classifier__min_samples_leaf': [1, 2, 3],
  'classifier__min_samples_split': [2, 3, 4],
  'classifier__max_depth': [3, 4, 5]}]

In [50]:
(combined_grid_search :=
 GridSearchCV(generic_cls,combined_grid, cv = folds, scoring='balanced_accuracy', verbose=1 )

 )

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier', None)]),
             param_grid=[{'classifier': [RandomForestClassifier()],
                          'classifier__max_depth': [2, 3, 4, 5],
                          'classifier__min_samples_leaf': [1, 2, 3],
                          'classifier__min_samples_split': [2, 3, 4],
                          'classifier__n_estimators': [10, 100, 500]},
                         {'classifier': [DecisionTreeClassifier()],
                          'classifier__max_depth': [3, 4, 5],
                          'classifier__min_samples_leaf': [1, 2, 3],
                          'classifier__min_samples_split': [2, 3, 4]}],
             scoring='balanced_accuracy', verbose=1)

In [51]:
combined_grid_search = GridSearchCV(generic_cls, combined_grid, cv = folds, scoring='roc_auc', n_jobs=-1, verbose=1)

combined_grid_search.fit(X_train_diabetes, y_train_diabetes)

Fitting 5 folds for each of 135 candidates, totalling 675 fits

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier', None)]),
             n_jobs=-1,
             param_grid=[{'classifier': [RandomForestClassifier()],
                          'classifier__max_depth': [2, 3, 4, 5],
                          'classifier__min_samples_leaf': [1, 2, 3],
                          'classifier__min_samples_split': [2, 3, 4],
                          'classifier__n_estimators': [10, 100, 500]},
                         {'classifier': [DecisionTreeClassifier()],
                          'classifier__max_depth': [3, 4, 5],
                          'classifier__min_samples_leaf': [1, 2, 3],
                          'classifier__min_samples_split': [2, 3, 4]}],
             scoring='roc_auc', verbose=1)

In [53]:
grid_search_tree.best_params_

{'max_depth': 4, 'min_samples_leaf': 3, 'min_samples_split': 3}

In [54]:
(combined_grid :=

 [forest_grid, tree_grid]


)

[{'classifier': [RandomForestClassifier()],
  'classifier__max_depth': [2, 3, 4, 5],
  'classifier__min_samples_leaf': [1, 2, 3],
  'classifier__min_samples_split': [2, 3, 4],
  'classifier__n_estimators': [10, 100, 500]},
 {'classifier': [DecisionTreeClassifier()],
  'classifier__min_samples_leaf': [1, 2, 3],
  'classifier__min_samples_split': [2, 3, 4],
  'classifier__max_depth': [3, 4, 5]}]

In [55]:
my_scores = ['accuracy', 'balanced_accuracy', 'roc_auc']



(diabetes_scores :=
 cross_validate(combined_grid_search, X_test_diabetes, y_test_diabetes,
                cv = folds,
                scoring=my_scores,
                verbose=0,
                n_jobs=-1,
                )
 >> rec.subset([f'test_{m}' for m in my_scores])
 >> rec.map(np.mean)
)

{'test_accuracy': np.float64(0.7273820536540241),
 'test_balanced_accuracy': np.float64(0.6447043010752689),
 'test_roc_auc': np.float64(nan)}

<font color="orange">
Your summary here.
</font>

### The best classifier out of the two options (random forest and decision tree) was the random forest classifier which was able to predict the classes with max depth of 5, classifier min sample leaf of 2, classifier min sample split of 2.  The cross validation map for our scores went as follows:
### test_accuracy: 0.71
### test_balanced_accuracy: 0.64
### test_roc_auc : NaN

## <font color="red"> Exercise 3 </font>

Now we build on the final exercise of the previous activity, where we performed a combined grid search over all of the classic classification methods.  Redo this, but this time add trees and forests of each type (alone, OvR, and OVO).

1. Create a combined grid on all 15 classifiers (5 classic classifiers + 5*OvR + 5*OvO).  
2. For `kNN`, add a number of `metric`s and `weights` to the grid.
3. Add 6 tree based classifiers to the grid search (tree + forest as well as OvR and OvO for each).
4. Perform the grid search over all the models and determing the winning model.
5. Evaluate the performance of the winning model using CV and write a summary interpreting each metric.

In [69]:
(knn_alone :=
  {'classifier': [KNeighborsClassifier()],
   'classifier__n_neighbors': list(range(2,12,2)),
    'classifier__metric': ['l1','l2'],
    'classifier__weights': ['uniform','distance']
  }
 )

{'classifier': [KNeighborsClassifier()],
 'classifier__n_neighbors': [2, 4, 6, 8, 10],
 'classifier__metric': ['l1', 'l2'],
 'classifier__weights': ['uniform', 'distance']}

In [70]:
knn_wrapped = {
    'classifier': [
        OneVsRestClassifier(KNeighborsClassifier()),
        OneVsOneClassifier(KNeighborsClassifier())
    ],
    'classifier__estimator__n_neighbors': list(range(2,12,2)),
    'classifier__estimator__metric': ['l1','l2'],
    'classifier__estimator__weights': ['uniform','distance']
}

In [ ]:
#(knn_wrapped :=
#    {'classifier': [OneVsOneClassifier(KNeighborsClassifier()),OneVsOneClassifier(KNeighborsClassifier())],
#     'classifier__estimator__n_neighbors': list(range(2,12,2)),
#     'classifier__estimator__metric': ['l1','l2'],
#     'classifier__estimator__weights': ['uniform','distance']
#    }
#)

{'classifier': [OneVsOneClassifier(estimator=KNeighborsClassifier()),
  OneVsOneClassifier(estimator=KNeighborsClassifier())],
 'classifier__estimator__n_neighbors': [2, 4, 6, 8, 10],
 'classifier__estimator__metric': ['l1', 'l2'],
 'classifier__estimator__weights': ['uniform', 'distance']}

In [71]:
(knn_grid :=
[knn_alone, knn_wrapped]
)

[{'classifier': [KNeighborsClassifier()],
  'classifier__n_neighbors': [2, 4, 6, 8, 10],
  'classifier__metric': ['l1', 'l2'],
  'classifier__weights': ['uniform', 'distance']},
 {'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
   OneVsOneClassifier(estimator=KNeighborsClassifier())],
  'classifier__estimator__n_neighbors': [2, 4, 6, 8, 10],
  'classifier__estimator__metric': ['l1', 'l2'],
  'classifier__estimator__weights': ['uniform', 'distance']}]

In [72]:
# Your code here (add cells as needed.)


(nontuning_grid :=  {'classifier' :
[LogisticRegression(max_iter=10000),
 OneVsRestClassifier(LogisticRegression(max_iter=10000)),
 OneVsOneClassifier(LogisticRegression(max_iter=10000)),
 GaussianNB(),
 OneVsRestClassifier(GaussianNB()),
 OneVsOneClassifier(GaussianNB()),
 LinearDiscriminantAnalysis(),
 OneVsRestClassifier(LinearDiscriminantAnalysis()),
 OneVsOneClassifier(LinearDiscriminantAnalysis()),
 QuadraticDiscriminantAnalysis(),
 OneVsRestClassifier(QuadraticDiscriminantAnalysis()),
 OneVsOneClassifier(QuadraticDiscriminantAnalysis())

]
}
)

{'classifier': [LogisticRegression(max_iter=10000),
  OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000)),
  OneVsOneClassifier(estimator=LogisticRegression(max_iter=10000)),
  GaussianNB(),
  OneVsRestClassifier(estimator=GaussianNB()),
  OneVsOneClassifier(estimator=GaussianNB()),
  LinearDiscriminantAnalysis(),
  OneVsRestClassifier(estimator=LinearDiscriminantAnalysis()),
  OneVsOneClassifier(estimator=LinearDiscriminantAnalysis()),
  QuadraticDiscriminantAnalysis(),
  OneVsRestClassifier(estimator=QuadraticDiscriminantAnalysis()),
  OneVsOneClassifier(estimator=QuadraticDiscriminantAnalysis())]}

In [ ]:
DecisionTreeClassifier().get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [57]:
(
 tree_alone :=
 { 'classifier' : [DecisionTreeClassifier()],
    'classifier__max_depth': [3, 5, 10, 15, 20],
    'classifier__min_samples_leaf': [1, 2, 4],
    'classifier__min_samples_split': [2, 5, 10]
 }
)

{'classifier': [DecisionTreeClassifier()],
 'classifier__max_depth': [3, 5, 10, 15, 20],
 'classifier__min_samples_leaf': [1, 2, 4],
 'classifier__min_samples_split': [2, 5, 10]}

In [58]:
(
 tree_wrapped :=

 { 'classifier' : [OneVsRestClassifier(DecisionTreeClassifier()),
                   OneVsOneClassifier(DecisionTreeClassifier())],
    'classifier__estimator__max_depth': [3, 5, 10, 15, 20],
    'classifier__estimator__min_samples_leaf': [1, 2, 4],
    'classifier__estimator__min_samples_split': [2, 5, 10]
 }

)

{'classifier': [OneVsRestClassifier(estimator=DecisionTreeClassifier()),
  OneVsOneClassifier(estimator=DecisionTreeClassifier())],
 'classifier__estimator__max_depth': [3, 5, 10, 15, 20],
 'classifier__estimator__min_samples_leaf': [1, 2, 4],
 'classifier__estimator__min_samples_split': [2, 5, 10]}

In [59]:
(tree_grid :=

 [tree_alone,tree_wrapped]


)

[{'classifier': [DecisionTreeClassifier()],
  'classifier__max_depth': [3, 5, 10, 15, 20],
  'classifier__min_samples_leaf': [1, 2, 4],
  'classifier__min_samples_split': [2, 5, 10]},
 {'classifier': [OneVsRestClassifier(estimator=DecisionTreeClassifier()),
   OneVsOneClassifier(estimator=DecisionTreeClassifier())],
  'classifier__estimator__max_depth': [3, 5, 10, 15, 20],
  'classifier__estimator__min_samples_leaf': [1, 2, 4],
  'classifier__estimator__min_samples_split': [2, 5, 10]}]

In [60]:
(
 forest_alone := {
    'classifier': [RandomForestClassifier()],
    'classifier__n_estimators': [50, 100, 200, 500],
    'classifier__max_depth': [5, 10, 15, 20],
    'classifier__min_samples_leaf': [1, 2, 4],
    'classifier__min_samples_split': [2, 5, 10]
}

)

{'classifier': [RandomForestClassifier()],
 'classifier__n_estimators': [50, 100, 200, 500],
 'classifier__max_depth': [5, 10, 15, 20],
 'classifier__min_samples_leaf': [1, 2, 4],
 'classifier__min_samples_split': [2, 5, 10]}

In [62]:
(
 forest_wrapped := {
    'classifier': [OneVsRestClassifier(RandomForestClassifier()),
                    OneVsOneClassifier(RandomForestClassifier())],
    'classifier__estimator__n_estimators': [50, 100, 200, 500],
    'classifier__estimator__max_depth': [5, 10, 15, 20],
    'classifier__estimator__min_samples_leaf': [1, 2, 4],
    'classifier__estimator__min_samples_split': [2, 5, 10]
}

)

{'classifier': [OneVsRestClassifier(estimator=RandomForestClassifier()),
  OneVsOneClassifier(estimator=RandomForestClassifier())],
 'classifier__estimator__n_estimators': [50, 100, 200, 500],
 'classifier__estimator__max_depth': [5, 10, 15, 20],
 'classifier__estimator__min_samples_leaf': [1, 2, 4],
 'classifier__estimator__min_samples_split': [2, 5, 10]}

In [65]:
(forest_grid :=

    [forest_alone,forest_wrapped]

 )

[{'classifier': [RandomForestClassifier()],
  'classifier__n_estimators': [50, 100, 200, 500],
  'classifier__max_depth': [5, 10, 15, 20],
  'classifier__min_samples_leaf': [1, 2, 4],
  'classifier__min_samples_split': [2, 5, 10]},
 {'classifier': [OneVsRestClassifier(estimator=RandomForestClassifier()),
   OneVsOneClassifier(estimator=RandomForestClassifier())],
  'classifier__estimator__n_estimators': [50, 100, 200, 500],
  'classifier__estimator__max_depth': [5, 10, 15, 20],
  'classifier__estimator__min_samples_leaf': [1, 2, 4],
  'classifier__estimator__min_samples_split': [2, 5, 10]}]

In [ ]:
#(combined_grid :=

#[forest_grid,tree_grid,knn_grid,nontuning_grid]
#)

[[{'classifier': [RandomForestClassifier()],
   'classifier__n_estimators': [50, 100],
   'classifier__max_depth': [5, 10]},
  {'classifier': [OneVsRestClassifier(estimator=RandomForestClassifier()),
    OneVsOneClassifier(estimator=RandomForestClassifier())],
   'classifier__estimator__n_estimators': [50, 100]}],
 [{'classifier': [DecisionTreeClassifier()],
   'classifier__max_depth': [3, 5, 10]},
  {'classifier': [OneVsRestClassifier(estimator=DecisionTreeClassifier()),
    OneVsOneClassifier(estimator=DecisionTreeClassifier())],
   'classifier__estimator__max_depth': [3, 5, 10]}],
 [{'classifier': [KNeighborsClassifier()],
   'classifier__n_neighbors': [2, 4, 6, 8, 10],
   'classifier__metric': ['l1', 'l2'],
   'classifier__weights': ['uniform', 'distance']},
  {'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
    OneVsOneClassifier(estimator=KNeighborsClassifier())],
   'classifier__estimator__n_neighbors': [2, 4, 6, 8, 10],
   'classifier__estimator__metric': ['l1', 'l2'],
   'classifier__estimator__weights': ['uniform', 'distance']}],
 {'classifier': [LogisticRegression(max_iter=10000),
   OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000)),
   OneVsOneClassifier(estimator=LogisticRegression(max_iter=10000)),
   GaussianNB(),
   OneVsRestClassifier(estimator=GaussianNB()),
   OneVsOneClassifier(estimator=GaussianNB()),
   LinearDiscriminantAnalysis(),
   OneVsRestClassifier(estimator=LinearDiscriminantAnalysis()),
   OneVsOneClassifier(estimator=LinearDiscriminantAnalysis()),
   QuadraticDiscriminantAnalysis(),
   OneVsRestClassifier(estimator=QuadraticDiscriminantAnalysis()),
   OneVsOneClassifier(estimator=QuadraticDiscriminantAnalysis())]}]

In [73]:
(combined_grid :=

forest_grid + tree_grid + knn_grid + [nontuning_grid]
#[forest_grid,tree_grid,knn_grid,nontuning_grid]



)

[{'classifier': [RandomForestClassifier()],
  'classifier__n_estimators': [50, 100, 200, 500],
  'classifier__max_depth': [5, 10, 15, 20],
  'classifier__min_samples_leaf': [1, 2, 4],
  'classifier__min_samples_split': [2, 5, 10]},
 {'classifier': [OneVsRestClassifier(estimator=RandomForestClassifier()),
   OneVsOneClassifier(estimator=RandomForestClassifier())],
  'classifier__estimator__n_estimators': [50, 100, 200, 500],
  'classifier__estimator__max_depth': [5, 10, 15, 20],
  'classifier__estimator__min_samples_leaf': [1, 2, 4],
  'classifier__estimator__min_samples_split': [2, 5, 10]},
 {'classifier': [DecisionTreeClassifier()],
  'classifier__max_depth': [3, 5, 10, 15, 20],
  'classifier__min_samples_leaf': [1, 2, 4],
  'classifier__min_samples_split': [2, 5, 10]},
 {'classifier': [OneVsRestClassifier(estimator=DecisionTreeClassifier()),
   OneVsOneClassifier(estimator=DecisionTreeClassifier())],
  'classifier__estimator__max_depth': [3, 5, 10, 15, 20],
  'classifier__estimator__min_samples_leaf': [1, 2, 4],
  'classifier__estimator__min_samples_split': [2, 5, 10]},
 {'classifier': [KNeighborsClassifier()],
  'classifier__n_neighbors': [2, 4, 6, 8, 10],
  'classifier__metric': ['l1', 'l2'],
  'classifier__weights': ['uniform', 'distance']},
 {'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
   OneVsOneClassifier(estimator=KNeighborsClassifier())],
  'classifier__estimator__n_neighbors': [2, 4, 6, 8, 10],
  'classifier__estimator__metric': ['l1', 'l2'],
  'classifier__estimator__weights': ['uniform', 'distance']},
 {'classifier': [LogisticRegression(max_iter=10000),
   OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000)),
   OneVsOneClassifier(estimator=LogisticRegression(max_iter=10000)),
   GaussianNB(),
   OneVsRestClassifier(estimator=GaussianNB()),
   OneVsOneClassifier(estimator=GaussianNB()),
   LinearDiscriminantAnalysis(),
   OneVsRestClassifier(estimator=LinearDiscriminantAnalysis()),
   OneVsOneClassifier(estimator=LinearDiscriminantAnalysis()),
   QuadraticDiscriminantAnalysis(),
   OneVsRestClassifier(estimator=QuadraticDiscriminantAnalysis()),
   OneVsOneClassifier(estimator=QuadraticDiscriminantAnalysis())]}]

In [74]:
(combined_grid_search :=
GridSearchCV(generic_cls, combined_grid,cv=folds, scoring='balanced_accuracy', verbose=1)
)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier', None)]),
             param_grid=[{'classifier': [RandomForestClassifier()],
                          'classifier__max_depth': [5, 10, 15, 20],
                          'classifier__min_samples_leaf': [1, 2, 4],
                          'classifier__min_samples_split': [2, 5, 10],
                          'classifier__n_estimators': [50,...
                                         OneVsOneClassifier(estimator=GaussianNB()),
                                         LinearDiscriminantAnalysis(),
                                         OneVsRestClassifier(estimator=LinearDiscriminantAnalysis()),
                                         OneVsOneClassifier(estimator=LinearDiscriminantAnalysis()),
                                         QuadraticDiscriminantAnalysis(),
                                         OneVsRestClassifier(estimator=QuadraticDiscriminantAnalysis()),
                                         OneVsOneClassifier(estimator=QuadraticDiscriminantAnalysis())]}],
             scoring='balanced_accuracy', verbose=1)

In [75]:
(combined_grid_search.fit(X_train_diabetes, y_train_diabetes))

Fitting 5 folds for each of 639 candidates, totalling 3195 fits

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier', None)]),
             param_grid=[{'classifier': [RandomForestClassifier()],
                          'classifier__max_depth': [5, 10, 15, 20],
                          'classifier__min_samples_leaf': [1, 2, 4],
                          'classifier__min_samples_split': [2, 5, 10],
                          'classifier__n_estimators': [50,...
                                         OneVsOneClassifier(estimator=GaussianNB()),
                                         LinearDiscriminantAnalysis(),
                                         OneVsRestClassifier(estimator=LinearDiscriminantAnalysis()),
                                         OneVsOneClassifier(estimator=LinearDiscriminantAnalysis()),
                                         QuadraticDiscriminantAnalysis(),
                                         OneVsRestClassifier(estimator=QuadraticDiscriminantAnalysis()),
                                         OneVsOneClassifier(estimator=QuadraticDiscriminantAnalysis())]}],
             scoring='balanced_accuracy', verbose=1)

In [76]:
print(f"Total models searched: {len(combined_grid_search.cv_results_['params'])}")
import pandas as pd
df = pd.DataFrame(combined_grid_search.cv_results_)
# This sorts them so you can see if QDA is at #2 or #20
print(df[['param_classifier', 'mean_test_score']].sort_values('mean_test_score', ascending=False))

Total models searched: 639
                                      param_classifier  mean_test_score
328  OneVsOneClassifier(estimator=RandomForestClass...         0.744806
330  OneVsOneClassifier(estimator=RandomForestClass...         0.742142
414  OneVsOneClassifier(estimator=RandomForestClass...         0.740972
240  OneVsRestClassifier(estimator=RandomForestClas...         0.740900
76                            RandomForestClassifier()         0.740713
..                                                 ...              ...
617  OneVsOneClassifier(estimator=KNeighborsClassif...         0.641027
597  OneVsRestClassifier(estimator=KNeighborsClassi...         0.641027
587  OneVsRestClassifier(estimator=KNeighborsClassi...         0.639031
607  OneVsOneClassifier(estimator=KNeighborsClassif...         0.639031
567                             KNeighborsClassifier()         0.639031

[639 rows x 2 columns]

In [77]:
metrics = ['accuracy',
           'balanced_accuracy',
           'f1_micro'
]


(all_combined_test_scores :=
 cross_validate(combined_grid_search, X_test_diabetes,y_test_diabetes,
                cv = folds,
                scoring = metrics,
                verbose =1,
                n_jobs = -1
 )
  >>rec.subset([f'test_{m}' for m in metrics])
  >>rec.map(np.mean)
 )

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed: 66.6min finished

{'test_accuracy': np.float64(0.7448658649398705),
 'test_balanced_accuracy': np.float64(0.710752688172043),
 'test_f1_micro': np.float64(0.7448658649398705)}

### Overall, the best classifier of the 89 models was the Random Forest Classifier with a test score of 0.74, the parameters of the classifier including a n_estimator of 50, min samples split of 5 and a max depth of 10. The metrics for the cross validation of the combined grid search went as follows:


### 'test_accuracy':  0.75   
### 'test_balanced_accuracy' : 0.71
###  'test_f1_micro' : 0.75